function [A,Ixx,Iyy,Ixy]=shoelace(body)
		
	N=size(body.vertices,1);
	
	A=0;
	Ixx=0;
	Iyy=0;
	Ixy=0;

	A=A+body.vertices(1,1)*(body.vertices(2,2)-body.vertices(N,2));
	A=A+body.vertices(N,1)*(body.vertices(1,2)-body.vertices(N-1,2));
	
	Imul=body.vertices(1,1)*body.vertices(2,2)...
		-body.vertices(2,1)*body.vertices(1,2);
	Ixx=Ixx+Imul*(body.vertices(1,2)^2+...
		body.vertices(1,2)*body.vertices(2,2)+...
		body.vertices(2,2)^2);
	Iyy=Iyy+Imul*(body.vertices(1,1)^2+...
		body.vertices(1,1)*body.vertices(2,1)+...
		body.vertices(2,1)^2);
	Ixy=Ixy+Imul*(body.vertices(1,1)*body.vertices(2,2)+...
		2*body.vertices(1,1)*body.vertices(1,2)+...
		2*body.vertices(2,1)*body.vertices(2,2)+...
		body.vertices(2,1)*body.vertices(1,2));
	
	Imul=body.vertices(N,1)*body.vertices(1,2)...
		-body.vertices(1,1)*body.vertices(N,2);
	Ixx=Ixx+Imul*(body.vertices(N,2)^2+...
		body.vertices(N,2)*body.vertices(1,2)+...
		body.vertices(1,2)^2);
	Iyy=Iyy+Imul*(body.vertices(N,1)^2+...
		body.vertices(N,1)*body.vertices(1,1)+...
		body.vertices(1,1)^2);
	Ixy=Ixy+Imul*(body.vertices(N,1)*body.vertices(1,2)+...
		2*body.vertices(N,1)*body.vertices(N,2)+...
		2*body.vertices(1,1)*body.vertices(1,2)+...
		body.vertices(1,1)*body.vertices(N,2));

	for i=2:N-1
		A=A+body.vertices(i,1)*(body.vertices(i+1,2)-body.vertices(i-1,2));
		Imul=body.vertices(i,1)*body.vertices(i+1,2)...
			-body.vertices(i+1,1)*body.vertices(i,2);
		Ixx=Ixx+Imul*(body.vertices(i,2)^2+...
			body.vertices(i,2)*body.vertices(i+1,2)+...
			body.vertices(i+1,2)^2);
		Iyy=Iyy+Imul*(body.vertices(i,1)^2+...
			body.vertices(i,1)*body.vertices(i+1,1)+...
			body.vertices(i+1,1)^2);
		Ixy=Ixy+Imul*(body.vertices(i,1)*body.vertices(i+1,2)+...
			2*body.vertices(i,1)*body.vertices(i,2)+...
			2*body.vertices(i+1,1)*body.vertices(i+1,2)+...
			body.vertices(i+1,1)*body.vertices(i,2));
	end

	A=A/2;
	Ixx=Ixx/12;
	Iyy=Iyy/12;
	Ixy=Ixy/24;
	
end
